### ISSUE TITLE
Does not take custom attachment payload

### ISSUE THREAD

**Issue by tlawrie** [IBM-UrbanCode/Slack-UCD#1]
The slack plugin should be able to take a custom attachment payload. This should be a large text field that is optional.

"attachments": [
        {
		"title": "title",
		"color": "good",
		"text": "Some result",
		"fallback" : "Plan text",
		"fields": [
				{"title": "Field 1: ", "value": "Field 1 Value", "short": true},
				{"title": "Field 2: ", "value": "Field 2 Value", "short": true}
		]
        }
	]

**Comment by nhmathis** [comment]
Pull request has been merged. 
Releasing now and closing issue.
