### ISSUE TITLE
Post custom messages to mutl

### ISSUE THREAD

**Issue by marcusdroy** [IBM-UrbanCode/Slack-UCD#3]
The slack plugin should be able to let you send a custom attachment to multiple channels by providing a list of slack channels or users to message to.

**Comment by nhmathis** [comment]
Hi @marcus174,

This has been merged and version 4 of the plugin has been released. As discussed in Issue #5, there was a `content` id that was expected in the Attachment payload. This is not standard to the expected payload. It instead should be `attachments`. I've updated the plugin to reflect as such. However, this means that your integration will likely need a small update. 

The multiple slack channel logic has also been improved to minimize redundant checks.

-Nick
