### ISSUE TITLE
Text for messages and add slack to application process

### ISSUE THREAD

**Issue by mcdougles** [IBM-UrbanCode/Slack-UCD#8]
Please add a Text message property (text + property values + scripting).
Add Slack notification possibility to Application process

**Comment by nhmathis** [comment]
Hi,

Any modifications to the Application Process's steps will require changes to the core product. The plugins in the IBM-UrbanCode GitHub or Microsite do not control any Application Process steps. 

Your best workaround will be creating a simple generic process, adding the Slack step to the generic process, and running the generic process through an Application Process. Through some property use, you can pass a value from the application process into the generic process.

-Nick

**Comment by mcdougles** [comment]
Hi

That's what I'm doing.

What about the text message?

Regards,

Zoltan

2017. dec. 12. du. 4:03 ezt írta ("Nick Mathison" <notifications@github.com

**Comment by nhmathis** [comment]
Which step are you using? Both steps allow you to supply a message value.

For the `Attachment Notification` step you will need to write the main body of the Slack message. [That documentation can be found here.](https://api.slack.com/docs/message-attachments) Specifically the Attachment structure section.

**Comment by mcdougles** [comment]
I'm using "Post Notification to Slack" step.

[image: Szövegközi kép 2]

Which property is for the message body?


2017-12-12 16:37 GMT+01:00 Nick Mathison <notifications@github.com>:

**Comment by nhmathis** [comment]
My apologies, I was incorrect in my earlier comment. The `Post Notification to Slack` step was intended to report the status of a Component Process version import. Thus, it will report the status (success/failure) of the component version specified.

You will want to use the `Post Attachment Notification to Slack` step to create a specific message. Use the documentation linked above to generate your own message.

**Comment by mcdougles** [comment]
Thank You.

2017-12-12 20:15 GMT+01:00 Nick Mathison <notifications@github.com>:

**Comment by nhmathis** [comment]
No problem.
